version: '3'
services:
  spacekadets:
    image: ${IMAGE_NAME}:latest
    networks:
      - nginx-proxy-overlay
    deploy:
      replicas: 1
      labels:
        xyz.tangerie.reverse_proxy.path: "/spacekadets"
        xyz.tangerie.reverse_proxy.port: "80"

networks:
  nginx-proxy-overlay:
    external: true
    driver: overlay
